version: '2'

services:
  money_tracker:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - "8888"
    links:
      - mysql
    env_file:
      - ./docker/money_tracker.env

  mysql:
    image: mysql:5.6
    env_file:
      - ./docker/mysql/mysql.env
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
